--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/WingsAnimated
build-by-default: true
branches:
- master
projects:
  WingsAnimated:
    path: ""
    icon: icon.png
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
