name: WingsAnimated
main: NurAzliYT\WingsAnimated\Loader
author: NurAzliYT
version: 1.0.0
api: 5.0.0

commands:
wingsanimated:
permission: wingsanimated.command

permissions:
wingsanimated.command:
default: op
